---
title: "GSS Data for 2021"
author: "Eshta Bhardwaj"
thanks: "Code and data available at: https://github.com/eshtab/GSSdata2021_analysis"
date: "April 20 2023"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
number-sections: true
format: 
  pdf:
    fig-pos: 'H' #this  makes sure that figures are placed directly underneath code
bibliography: "references.bib"
---



```{r}
#| include: FALSE
#| warning: FALSE
#| message: FALSE

#### Workspace set-up ####

library(tidyverse)
library(janitor)
library(modelsummary)
library(lubridate)

```

# Introduction

The United States of America has a history of political polarization. These divisions are often attributed to diverging worldviews related to race, class, gender, and more. In order to understand the opinions of the American society, it is important to analyze data collected on topics like political beliefs. 

The General Social Survey is conducted nationwide in the US to capture public opinion on a variety of indicators through surveys. This data acts as 

The introduction is self-contained and tells a reader everything they need to know including: 1) broader context to motivate; 2) some detail about what the paper is about; 3) a clear gap that needs to be filled; 4) what was done; 5) what was found; 6) why it is important; 7) the structure of the paper. A reader should be able to read only the introduction and know what was done, why, and what was found. Likely 3 or 4 paragraphs, or 10 per cent of total.


# Data Collection 

## Overview

## Survey Description

## Population

## Frame

## Stratification

## Sample

## Non-response and Imputation

## Survey Design

## Bias

# Data Description

## Overview

## Variables of Interest

## Missing Data

## Data Cleaning

# Data Processing

# Results

# Discussion

# Conclusion

\newpage

\appendix

# Appendix {.unnumbered}

# Additional details

\newpage

# References
